import { describe, expect, test } from "bun:test"
import path from "node:path"

const promptPath = path.resolve(import.meta.dir, "../../../src/session/prompt.ts")
const queryPath = path.resolve(import.meta.dir, "../../../src/kilocode/tool/lcm-query.ts")
const expandQueryPath = path.resolve(import.meta.dir, "../../../src/kilocode/tool/lcm-expand-query.ts")
const hostPath = path.resolve(import.meta.dir, "../../../src/kilocode/session/lcm/prompt-host.ts")
const servicePath = path.resolve(import.meta.dir, "../../../src/kilocode/session/lcm/service.ts")

describe("LCM prompt seam", () => {
  test("projects only after upstream request assembly and before provider execution", async () => {
    const source = await Bun.file(promptPath).text()
    const converted = source.indexOf("MessageV2.toModelMessagesEffect")
    const finalStep = source.indexOf("content: MAX_STEPS_PROMPT", converted)
    const projected = source.indexOf("ConversationMemoryPromptHost.prepare")
    const processed = source.indexOf("handle.process({", projected)

    expect(converted).toBeGreaterThan(0)
    expect(finalStep).toBeGreaterThan(converted)
    expect(projected).toBeGreaterThan(converted)
    expect(processed).toBeGreaterThan(projected)
    expect(source.slice(processed, processed + 1_200)).toContain("messages: preparedRequest.messages")
    expect(source).toContain("step >= maxSteps && !isLcmRecoveryAgent(agent.name)")
    expect(source).not.toMatch(/\bMAX_STEPS\b/)
  })

  test("records successful consumption before a superseded queued handoff", async () => {
    const source = await Bun.file(promptPath).text()
    const completed = source.indexOf("yield* preparedRequest.complete(true)")
    const handoff = source.indexOf("KiloSessionPromptQueue.hasFollowup", completed)

    expect(completed).toBeGreaterThan(0)
    expect(handoff).toBeGreaterThan(completed)
    expect(source.slice(handoff, handoff + 300)).toContain('closeReasons.set(sessionID, "superseded")')
  })

  test("recovery budgets do not take over ordinary parent turn control", async () => {
    const source = await Bun.file(promptPath).text()
    expect(source).toContain("const tools = yield* SessionTools.resolve({")
    expect(source).toContain('toolChoice: format.type === "json_schema" ? "required" : undefined')
    expect(source).not.toContain("lcmQueryAnswerOnly")
    expect(source).not.toContain("lcmQuerySettlement")
    expect(source).not.toContain("LCM_QUERY_ANSWER_ONLY_PROMPT")
    expect(source).not.toContain("delete tools[name]")
  })

  test("keeps hidden recovery phase orchestration out of the shared prompt loop", async () => {
    const source = await Bun.file(promptPath).text()

    expect(source).not.toContain("lcmRecoverySynthesisOnly")
    expect(source).not.toContain("LCM_RECOVERY_SYNTHESIS_PROMPT")
    expect(source).toContain("lcmRecoveryHardStepExceeded(agent.name, step, maxSteps)")
    const malformedStop = source.indexOf("lcmRecoveryInvalidToolInputLimitReached(lastUser.agent, msgs)")
    const nextStep = source.indexOf("step++", malformedStop)
    expect(malformedStop).toBeGreaterThan(0)
    expect(nextStep).toBeGreaterThan(malformedStop)
  })

  test("synthesizes in the evidence-bearing child before creating a repair sibling", async () => {
    const source = await Bun.file(queryPath).text()
    const synthesis = source.indexOf(
      "text: recoverySynthesisRequest(question, candidateLedger, fullCoverageGaps, parentContext)",
    )
    const child = source.lastIndexOf("sessionID: child.id", synthesis)
    const locked = source.indexOf("agent: LCM_RECOVERY_FINALIZER_AGENT", synthesis)
    const repair = source.indexOf("const finalizerSessionID = yield* ensureFinalizer", locked)

    expect(synthesis).toBeGreaterThan(0)
    expect(child).toBeGreaterThan(0)
    expect(child).toBeLessThan(synthesis)
    expect(locked).toBeGreaterThan(synthesis)
    expect(repair).toBeGreaterThan(locked)
  })

  test("keeps the focused question authoritative across isolated query phases", async () => {
    const query = await Bun.file(queryPath).text()
    const expandQuery = await Bun.file(expandQueryPath).text()

    expect(query.match(/\[LCM_RECOVERY_PARENT_REQUEST_METADATA\]: parentContext/g)?.length).toBe(2)
    expect(query).toContain("[LCM_RECOVERY_RESULT_INFORMED_METADATA]: true")
    expect(query).toContain("const semanticAssignment = lcmRecoverySemanticAssignment(question, parentContext)")
    expect(query).not.toContain("lcmRecoveryNeedsSemanticAuthorityReview")
    expect(query).not.toContain("const reviewEvidence =")
    expect(query).toContain("question: retrievalQuery")
    expect(query).toContain("initialEvidence: initialCandidateLedger")
    expect(query).toContain("synthesis: researchSynthesis")
    expect(query).not.toContain('synthesis: ""')
    expect(query).not.toContain("fullCoverageReview")
    expect(query).toContain("verified: constrainRecoveryCoverage(verified, fullCoverageGaps)")
    expect(query).toContain("fullCoverageGaps,")
    expect(expandQuery).toContain("semanticQuestion = lcmRecoverySemanticQuestion")
    expect(expandQuery).toContain("query = lcmRecoveryRetrievalQuestion(bound, parentRequest)")
    expect(expandQuery).toContain("semanticAuthority = bound")
    expect(expandQuery).toContain("const sourceRanges = trustedStructuralUnit?.semanticRanges ?? requestedSourceRanges")
    expect(expandQuery).not.toContain("resultInformed = lcmRecoveryResultInformed")
    expect(expandQuery).not.toContain("resultInformedScopeReplay")
    expect(expandQuery).toContain("if (resultInformed)")
    expect(expandQuery).toContain("trustedStructuralSemanticQuestion(semanticAuthority")
    expect(expandQuery).toMatch(/generated = yield\* runSemantic\(\s*semanticQuestion,/)
    expect(expandQuery).toContain("trustedStructuralReductionQuestion({")
    expect(expandQuery).toContain("trustedStructuralVerificationQuestion({")
    expect(expandQuery).toContain("question: semanticAuthority,")
    expect(expandQuery).toContain('"structural_unit_reduction"')
    expect(expandQuery).toContain('"structural_unit_verification"')
    expect(expandQuery).toContain("const reductionFallbackCandidates =")
    expect(expandQuery).toContain("reserveLcmRecoverySemanticInferences(ctx.sessionID")
    expect(expandQuery).toContain("trustedStructuralShardRepairQuestion({")
    expect(expandQuery).toContain("hierarchicalSemanticShardRepairPlan({")
    expect(expandQuery).toContain("lcmRecoveryBudgetStats(ctx.sessionID)")
    expect(expandQuery).toContain('repair.reason === "unconfirmed_none"')
    expect(expandQuery).toContain('repair.reason === "unconfirmed_partial"')
    expect(expandQuery).toContain("hierarchicalSemanticPassRepairPlan({")
    expect(expandQuery).toContain("trustedStructuralPassRepairQuestion({")
    expect(expandQuery).toContain("repairPlan.length, recoveryLimits")
    expect(expandQuery).toContain("hierarchicalReconciledAnswer({")
    expect(expandQuery).toContain("const shardAnalyses = primaryShardAnalyses.flatMap")
    expect(expandQuery).toContain("additiveStructuralShardResult({")
    expect(expandQuery).toContain("const independentShardAnalyses = primaryShardAnalyses.flatMap")
    expect(expandQuery).toContain("hierarchicalEvidencePasses = independentShardAnalyses.flatMap")
    expect(expandQuery).toContain("hierarchicalReductionShardEvidence({")
    expect(expandQuery).toContain('exactFallback: semanticQueryExcerpts(analysis.shard, "shard")')
    expect(expandQuery).toContain("reductionFallbackCandidates,")
    expect(expandQuery).toContain("semanticPassDiagnostics")
    expect(expandQuery).toContain("semanticInwardScope(item, boundedClusters[index + 1]")
  })

  test("uses blocking LCM hard maintenance without a legacy compaction fallback", async () => {
    const source = await Bun.file(promptPath).text()
    const host = await Bun.file(hostPath).text()
    const projected = host.indexOf("input.memory.project")
    const hardFailure = host.indexOf("lcm_hard_limit_unresolved", projected)
    const retry = host.indexOf("input.memory.maintain", hardFailure)

    expect(projected).toBeGreaterThan(0)
    expect(hardFailure).toBeGreaterThan(projected)
    expect(retry).toBeGreaterThan(hardFailure)
    expect(host).toContain('projection.type !== "projected"')
    expect(host).not.toContain("compaction.create")
    expect(source).toContain('if (result === "compact")')
    expect(source).toContain("if (conversationMemoryEnabled)")
    expect(source).toContain("enabled: conversationMemorySessionEnabled")
    expect(source).toContain("if (!conversationMemorySessionEnabled)")
    expect(source).toContain("lcm_recovery_context_limit")
  })

  test("retains the upstream compact result and verifies the stricter external retry", async () => {
    const source = await Bun.file(promptPath).text()
    const host = await Bun.file(hostPath).text()
    expect(source).toContain('contextManagement: conversationMemoryEnabled ? "external" : "upstream"')
    expect(source).toContain("const conversationMemorySessionEnabled = lcmSessionContextManagementEnabled(")
    expect(source).toContain("const transcript = conversationMemorySessionEnabled")
    expect(source).toContain(
      "size > REQUEST_PRUNE_BYTES && (!conversationMemoryEnabled || conversationMemorySessionEnabled)",
    )
    expect(source).toContain("preserving oversized isolated recovery transcript")
    expect(source).toContain('result === "compact"')
    expect(source).not.toContain('result === "provider_overflow"')
    expect(host).toContain('reason: input.state.overflowRetry ? "hard" : "soft"')
    expect(host).toContain("retryTokens < retry.requestTokens")
    expect(host).toContain("projection.revision.id === retry.revisionID")
  })

  test("keeps routine projection reuse out of activity timeline records", async () => {
    const source = await Bun.file(servicePath).text()
    expect(source).not.toContain("Conversation Memory represented earlier conversation with summaries.")
    expect(source).toContain("Conversation Memory prepared an earlier-history summary.")
    expect(source).toContain('reason: input.reason === "hard" || hard ? "hard_built" : "soft_ready"')
  })

  test("records direct hard-pressure preparation in the activity timeline", async () => {
    const source = await Bun.file(servicePath).text()
    const hard = source.indexOf("if (hard) {")
    const build = source.indexOf("const revision = yield* Effect.promise", hard)
    const activity = source.indexOf("synced.store.appendActivity", build)
    const projected = source.indexOf('projectCurrent("hard")', activity)

    expect(hard).toBeGreaterThan(0)
    expect(build).toBeGreaterThan(hard)
    expect(activity).toBeGreaterThan(build)
    expect(projected).toBeGreaterThan(activity)
    expect(source.slice(activity, projected)).toContain('kind: changed ? "frontier_advanced" : "intervention"')
    expect(source.slice(activity, projected)).toContain("hard-level preparation")
    expect(source.slice(activity, projected)).toContain("events.publish(LcmEvent.Activity")
  })
})
